name: auto_commit
on:
  schedule:
    # 日本時間25時00分
    - cron: '0 16 * * *'

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: commit
        run: |
          bash auto-commit/main.sh
